[rewrite_local]
^https?:\/\/api\.(picsart|meituapi)\.com\/.+\/(vip|purchase|subscription|billing|users\/main) url script-response-body https://raw.githubusercontent.com/Quantumult-X-LK/master/Scripts/langkhach/picsart.js

[mitm]
hostname = *.picsart.com, api.picsart.com, *.meituapi.com, api.meituapi.com
